name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install
        run: npm ci

      - name: Test (optional)
        run: npm test --if-present

      - name: Build
        run: npm run build

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase image name
        run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare image tags
        id: prep
        shell: bash
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}"
          echo "tags<<EOF" >> "$GITHUB_OUTPUT"
          echo "${IMAGE}:latest" >> "$GITHUB_OUTPUT"
          echo "${IMAGE}:${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          build-args: |
            VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}


      - name: Trigger infra workflow (deploy-frontend)
        env:
          INFRA_REPO_TOKEN: ${{ secrets.INFRA_REPO_TOKEN }}
        run: |
          curl -sS -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${INFRA_REPO_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/RSO-Simon/infrastructure/actions/workflows/deploy-frontend.yml/dispatches \
            -d "{\"ref\":\"main\",\"inputs\":{\"imageTag\":\"${GITHUB_SHA}\"}}"
